// Version 1: complete pinned Ibex RVFI boundary; counters lane i = [32*i +: 32].
module soc_ibex_rvfi_local import ibex_pkg::*; import ibex_cheriot_pkg::*; (
  input logic clk_i,
  input logic rst_ni,
  input logic test_en_i,
  input prim_ram_1p_pkg::ram_1p_cfg_req_t [ibex_pkg::IC_NUM_WAYS-1:0] ram_cfg_icache_tag_i,
  output prim_ram_1p_pkg::ram_1p_cfg_rsp_t [ibex_pkg::IC_NUM_WAYS-1:0] ram_cfg_icache_tag_o,
  input prim_ram_1p_pkg::ram_1p_cfg_req_t [ibex_pkg::IC_NUM_WAYS-1:0] ram_cfg_icache_data_i,
  output prim_ram_1p_pkg::ram_1p_cfg_rsp_t [ibex_pkg::IC_NUM_WAYS-1:0] ram_cfg_icache_data_o,
  input ibex_mubi_t cheriot_enable_i,
  input logic [31:0] hart_id_i,
  input logic [31:0] boot_addr_i,
  input logic [31:0] trvk_heap_base_addr_i,
  output logic instr_req_o,
  input logic instr_gnt_i,
  input logic instr_rvalid_i,
  output logic [31:0] instr_addr_o,
  input logic [31:0] instr_rdata_i,
  input logic [6:0] instr_rdata_intg_i,
  input logic instr_err_i,
  output logic data_req_o,
  input logic data_gnt_i,
  input logic data_rvalid_i,
  output logic data_we_o,
  output logic [3:0] data_be_o,
  output logic [31:0] data_addr_o,
  output logic [31:0] data_wdata_o,
  output logic [6:0] data_wdata_intg_o,
  output logic data_tag_o,
  input logic [31:0] data_rdata_i,
  input logic [6:0] data_rdata_intg_i,
  input logic data_tag_i,
  input logic data_err_i,
  output logic trvk_revbm_req_o,
  input logic trvk_revbm_gnt_i,
  input logic trvk_revbm_rvalid_i,
  output logic [31:0] trvk_revbm_addr_o,
  input logic [31:0] trvk_revbm_rdata_i,
  input logic [6:0] trvk_revbm_rdata_intg_i,
  input logic trvk_revbm_err_i,
  input logic irq_software_i,
  input logic irq_timer_i,
  input logic irq_external_i,
  input logic [14:0] irq_fast_i,
  input logic irq_nm_i,
  input logic scramble_key_valid_i,
  input logic [SCRAMBLE_KEY_W-1:0] scramble_key_i,
  input logic [SCRAMBLE_NONCE_W-1:0] scramble_nonce_i,
  output logic scramble_req_o,
  input logic debug_req_i,
  output crash_dump_t crash_dump_o,
  output logic double_fault_seen_o,
  output logic [63:0] irq_decision_serial,
  output logic [63:0] irq_retirement_serial,
  output logic rvfi_valid,
  output logic [63:0] rvfi_order,
  output logic [31:0] rvfi_insn,
  output logic rvfi_trap,
  output logic rvfi_halt,
  output logic rvfi_intr,
  output logic [ 1:0] rvfi_mode,
  output logic [ 1:0] rvfi_ixl,
  output logic [ 4:0] rvfi_rs1_addr,
  output logic [ 4:0] rvfi_rs2_addr,
  output logic [ 4:0] rvfi_rs3_addr,
  output logic [31:0] rvfi_rs1_rdata,
  output logic [31:0] rvfi_rs2_rdata,
  output logic [31:0] rvfi_rs3_rdata,
  output logic [$bits(ibex_cheriot_pkg::cap_t)-1:0] rvfi_rs1_rcap,
  output logic [$bits(ibex_cheriot_pkg::cap_t)-1:0] rvfi_rs2_rcap,
  output logic [$bits(ibex_cheriot_pkg::cap_t)-1:0] rvfi_rd_wcap,
  output logic [ 4:0] rvfi_rd_addr,
  output logic [31:0] rvfi_rd_wdata,
  output logic [31:0] rvfi_pc_rdata,
  output logic [31:0] rvfi_pc_wdata,
  output logic [31:0] rvfi_mem_addr,
  output logic [ 3:0] rvfi_mem_rmask,
  output logic [ 3:0] rvfi_mem_wmask,
  output logic [31:0] rvfi_mem_rdata,
  output logic [31:0] rvfi_mem_wdata,
  output logic rvfi_mem_is_cap,
  output logic [$bits(ibex_cheriot_pkg::cap_t)-1:0] rvfi_mem_rcap,
  output logic [$bits(ibex_cheriot_pkg::cap_t)-1:0] rvfi_mem_wcap,
  output logic [31:0] rvfi_ext_pre_mip,
  output logic [31:0] rvfi_ext_post_mip,
  output logic rvfi_ext_nmi,
  output logic rvfi_ext_nmi_int,
  output logic rvfi_ext_debug_req,
  output logic rvfi_ext_debug_mode,
  output logic rvfi_ext_rf_wr_suppress,
  output logic [63:0] rvfi_ext_mcycle,
  output logic [319:0] rvfi_ext_mhpmcounters,
  output logic [319:0] rvfi_ext_mhpmcountersh,
  output logic rvfi_ext_ic_scr_key_valid,
  output logic rvfi_ext_irq_valid,
  output logic rvfi_ext_expanded_insn_valid,
  output logic [15:0] rvfi_ext_expanded_insn,
  output logic rvfi_ext_expanded_insn_last,
  input ibex_mubi_t fetch_enable_i,
  input ibex_mubi_t mcounteren_writable_i,
  output logic alert_minor_o,
  output logic alert_major_internal_o,
  output logic alert_major_bus_o,
  output logic core_sleep_o,
  input logic scan_rst_ni,
  output ibex_mubi_t lockstep_cmp_en_o,
  output logic data_req_shadow_o,
  output logic data_we_shadow_o,
  output logic [3:0] data_be_shadow_o,
  output logic [31:0] data_addr_shadow_o,
  output logic [31:0] data_wdata_shadow_o,
  output logic [6:0] data_wdata_intg_shadow_o,
  output logic instr_req_shadow_o,
  output logic [31:0] instr_addr_shadow_o
);
  logic [31:0] rvfi_ext_mhpmcounters_unpacked [10];
  logic [31:0] rvfi_ext_mhpmcountersh_unpacked [10];
  assign rvfi_ext_mhpmcounters[0 +: 32] = rvfi_ext_mhpmcounters_unpacked[0];
  assign rvfi_ext_mhpmcounters[32 +: 32] = rvfi_ext_mhpmcounters_unpacked[1];
  assign rvfi_ext_mhpmcounters[64 +: 32] = rvfi_ext_mhpmcounters_unpacked[2];
  assign rvfi_ext_mhpmcounters[96 +: 32] = rvfi_ext_mhpmcounters_unpacked[3];
  assign rvfi_ext_mhpmcounters[128 +: 32] = rvfi_ext_mhpmcounters_unpacked[4];
  assign rvfi_ext_mhpmcounters[160 +: 32] = rvfi_ext_mhpmcounters_unpacked[5];
  assign rvfi_ext_mhpmcounters[192 +: 32] = rvfi_ext_mhpmcounters_unpacked[6];
  assign rvfi_ext_mhpmcounters[224 +: 32] = rvfi_ext_mhpmcounters_unpacked[7];
  assign rvfi_ext_mhpmcounters[256 +: 32] = rvfi_ext_mhpmcounters_unpacked[8];
  assign rvfi_ext_mhpmcounters[288 +: 32] = rvfi_ext_mhpmcounters_unpacked[9];
  assign rvfi_ext_mhpmcountersh[0 +: 32] = rvfi_ext_mhpmcountersh_unpacked[0];
  assign rvfi_ext_mhpmcountersh[32 +: 32] = rvfi_ext_mhpmcountersh_unpacked[1];
  assign rvfi_ext_mhpmcountersh[64 +: 32] = rvfi_ext_mhpmcountersh_unpacked[2];
  assign rvfi_ext_mhpmcountersh[96 +: 32] = rvfi_ext_mhpmcountersh_unpacked[3];
  assign rvfi_ext_mhpmcountersh[128 +: 32] = rvfi_ext_mhpmcountersh_unpacked[4];
  assign rvfi_ext_mhpmcountersh[160 +: 32] = rvfi_ext_mhpmcountersh_unpacked[5];
  assign rvfi_ext_mhpmcountersh[192 +: 32] = rvfi_ext_mhpmcountersh_unpacked[6];
  assign rvfi_ext_mhpmcountersh[224 +: 32] = rvfi_ext_mhpmcountersh_unpacked[7];
  assign rvfi_ext_mhpmcountersh[256 +: 32] = rvfi_ext_mhpmcountersh_unpacked[8];
  assign rvfi_ext_mhpmcountersh[288 +: 32] = rvfi_ext_mhpmcountersh_unpacked[9];
  ibex_irq_serial_sideband #(.WritebackStage(1'b0)) u_irq_serial (
    .clk_i(clk_i), .rst_ni(rst_ni),
    .external_decision_i(u_ibex.u_ibex_core.id_stage_i.controller_i.pc_set_o &
      u_ibex.u_ibex_core.id_stage_i.controller_i.csr_save_cause_o &
      (u_ibex.u_ibex_core.id_stage_i.controller_i.exc_pc_mux_o == EXC_PC_IRQ) &
      (u_ibex.u_ibex_core.id_stage_i.controller_i.exc_cause_o == ExcCauseIrqExternalM)),
    .any_irq_pc_decision_i(u_ibex.u_ibex_core.pc_set &
      (u_ibex.u_ibex_core.pc_mux_id == PC_EXC) &
      (u_ibex.u_ibex_core.exc_pc_mux_id == EXC_PC_IRQ)),
    .instr_first_cycle_id_i(u_ibex.u_ibex_core.instr_first_cycle_id),
    .rvfi_id_done_i(u_ibex.u_ibex_core.rvfi_id_done),
    .rvfi_wb_done_i(u_ibex.u_ibex_core.rvfi_wb_done),
    .rvfi_valid_i(rvfi_valid), .rvfi_intr_i(rvfi_intr),
    .decision_serial_o(irq_decision_serial),
    .retirement_serial_o(irq_retirement_serial)
  );
  ibex_top #(.PMPEnable(0), .RV32E(0), .ICache(0), .SecureIbex(0)) u_ibex (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .test_en_i(test_en_i),
    .ram_cfg_icache_tag_i(ram_cfg_icache_tag_i),
    .ram_cfg_icache_tag_o(ram_cfg_icache_tag_o),
    .ram_cfg_icache_data_i(ram_cfg_icache_data_i),
    .ram_cfg_icache_data_o(ram_cfg_icache_data_o),
    .cheriot_enable_i(cheriot_enable_i),
    .hart_id_i(hart_id_i),
    .boot_addr_i(boot_addr_i),
    .trvk_heap_base_addr_i(trvk_heap_base_addr_i),
    .instr_req_o(instr_req_o),
    .instr_gnt_i(instr_gnt_i),
    .instr_rvalid_i(instr_rvalid_i),
    .instr_addr_o(instr_addr_o),
    .instr_rdata_i(instr_rdata_i),
    .instr_rdata_intg_i(instr_rdata_intg_i),
    .instr_err_i(instr_err_i),
    .data_req_o(data_req_o),
    .data_gnt_i(data_gnt_i),
    .data_rvalid_i(data_rvalid_i),
    .data_we_o(data_we_o),
    .data_be_o(data_be_o),
    .data_addr_o(data_addr_o),
    .data_wdata_o(data_wdata_o),
    .data_wdata_intg_o(data_wdata_intg_o),
    .data_tag_o(data_tag_o),
    .data_rdata_i(data_rdata_i),
    .data_rdata_intg_i(data_rdata_intg_i),
    .data_tag_i(data_tag_i),
    .data_err_i(data_err_i),
    .trvk_revbm_req_o(trvk_revbm_req_o),
    .trvk_revbm_gnt_i(trvk_revbm_gnt_i),
    .trvk_revbm_rvalid_i(trvk_revbm_rvalid_i),
    .trvk_revbm_addr_o(trvk_revbm_addr_o),
    .trvk_revbm_rdata_i(trvk_revbm_rdata_i),
    .trvk_revbm_rdata_intg_i(trvk_revbm_rdata_intg_i),
    .trvk_revbm_err_i(trvk_revbm_err_i),
    .irq_software_i(irq_software_i),
    .irq_timer_i(irq_timer_i),
    .irq_external_i(irq_external_i),
    .irq_fast_i(irq_fast_i),
    .irq_nm_i(irq_nm_i),
    .scramble_key_valid_i(scramble_key_valid_i),
    .scramble_key_i(scramble_key_i),
    .scramble_nonce_i(scramble_nonce_i),
    .scramble_req_o(scramble_req_o),
    .debug_req_i(debug_req_i),
    .crash_dump_o(crash_dump_o),
    .double_fault_seen_o(double_fault_seen_o),
    .rvfi_valid(rvfi_valid),
    .rvfi_order(rvfi_order),
    .rvfi_insn(rvfi_insn),
    .rvfi_trap(rvfi_trap),
    .rvfi_halt(rvfi_halt),
    .rvfi_intr(rvfi_intr),
    .rvfi_mode(rvfi_mode),
    .rvfi_ixl(rvfi_ixl),
    .rvfi_rs1_addr(rvfi_rs1_addr),
    .rvfi_rs2_addr(rvfi_rs2_addr),
    .rvfi_rs3_addr(rvfi_rs3_addr),
    .rvfi_rs1_rdata(rvfi_rs1_rdata),
    .rvfi_rs2_rdata(rvfi_rs2_rdata),
    .rvfi_rs3_rdata(rvfi_rs3_rdata),
    .rvfi_rs1_rcap(rvfi_rs1_rcap),
    .rvfi_rs2_rcap(rvfi_rs2_rcap),
    .rvfi_rd_wcap(rvfi_rd_wcap),
    .rvfi_rd_addr(rvfi_rd_addr),
    .rvfi_rd_wdata(rvfi_rd_wdata),
    .rvfi_pc_rdata(rvfi_pc_rdata),
    .rvfi_pc_wdata(rvfi_pc_wdata),
    .rvfi_mem_addr(rvfi_mem_addr),
    .rvfi_mem_rmask(rvfi_mem_rmask),
    .rvfi_mem_wmask(rvfi_mem_wmask),
    .rvfi_mem_rdata(rvfi_mem_rdata),
    .rvfi_mem_wdata(rvfi_mem_wdata),
    .rvfi_mem_is_cap(rvfi_mem_is_cap),
    .rvfi_mem_rcap(rvfi_mem_rcap),
    .rvfi_mem_wcap(rvfi_mem_wcap),
    .rvfi_ext_pre_mip(rvfi_ext_pre_mip),
    .rvfi_ext_post_mip(rvfi_ext_post_mip),
    .rvfi_ext_nmi(rvfi_ext_nmi),
    .rvfi_ext_nmi_int(rvfi_ext_nmi_int),
    .rvfi_ext_debug_req(rvfi_ext_debug_req),
    .rvfi_ext_debug_mode(rvfi_ext_debug_mode),
    .rvfi_ext_rf_wr_suppress(rvfi_ext_rf_wr_suppress),
    .rvfi_ext_mcycle(rvfi_ext_mcycle),
    .rvfi_ext_mhpmcounters(rvfi_ext_mhpmcounters_unpacked),
    .rvfi_ext_mhpmcountersh(rvfi_ext_mhpmcountersh_unpacked),
    .rvfi_ext_ic_scr_key_valid(rvfi_ext_ic_scr_key_valid),
    .rvfi_ext_irq_valid(rvfi_ext_irq_valid),
    .rvfi_ext_expanded_insn_valid(rvfi_ext_expanded_insn_valid),
    .rvfi_ext_expanded_insn(rvfi_ext_expanded_insn),
    .rvfi_ext_expanded_insn_last(rvfi_ext_expanded_insn_last),
    .fetch_enable_i(fetch_enable_i),
    .mcounteren_writable_i(mcounteren_writable_i),
    .alert_minor_o(alert_minor_o),
    .alert_major_internal_o(alert_major_internal_o),
    .alert_major_bus_o(alert_major_bus_o),
    .core_sleep_o(core_sleep_o),
    .scan_rst_ni(scan_rst_ni),
    .lockstep_cmp_en_o(lockstep_cmp_en_o),
    .data_req_shadow_o(data_req_shadow_o),
    .data_we_shadow_o(data_we_shadow_o),
    .data_be_shadow_o(data_be_shadow_o),
    .data_addr_shadow_o(data_addr_shadow_o),
    .data_wdata_shadow_o(data_wdata_shadow_o),
    .data_wdata_intg_shadow_o(data_wdata_intg_shadow_o),
    .instr_req_shadow_o(instr_req_shadow_o),
    .instr_addr_shadow_o(instr_addr_shadow_o)
  );
endmodule
