"""Protocol-driven system builder inputs and planning primitives."""

from .input_model import (
    AddressMode,
    AddressRequest,
    ClockDomain,
    InterfaceSpec,
    InputValidationError,
    ModuleKind,
    ModuleSpec,
    PortAnnotation,
    PortDirection,
    ResetDomain,
    SourceSet,
    SystemSpec,
    UnknownPortPolicySpec,
    load_system_spec,
)
from .profiles import (
    ChannelRule,
    InterfaceRole,
    MatchSource,
    PortResolution,
    PortRule,
    ProfileAddressRule,
    ProfileRegistry,
    ProtocolProfile,
)
from .builtin_profiles import builtin_profile_registry
from .backend_registry import (
    BackendRegistry, BackendSpec, CapabilityMismatch, builtin_backend_registry,
)
from .classification import ModuleClassification, classify_modules
from .planner import InterfaceBinding, PortBinding, SystemPlan, plan_system
from .emitter import emit_system
from .rfuzz_bridge import emit_rfuzz_metadata, generate_rfuzz_testcase
from .instrumentation_bridge import (
    run_instrumentation, run_soc_instrumentation, update_generation_report,
)
from .unknown_ports import (
    DecisionStatus,
    UnknownInputRequest,
    UnknownPortAction,
    UnknownPortDecision,
    decide_unknown_port,
    unknown_port_report,
)
from .addressing import (
    AddressIntent,
    AddressPlan,
    AddressPlanEntry,
    AddressWindow,
    allocate_addresses,
)
from .graph import (
    ConnectionEdge,
    ConnectionKind,
    ConnectionRequest,
    ConstraintKind,
    EndpointRef,
    SignalConstraint,
    SignalEndpoint,
    SystemGraph,
    build_system_graph,
)
from .discovery import (
    DiscoveredInstance,
    DiscoveredModule,
    DiscoveredPort,
    DiscoveryResult,
    discover_system,
)
from .analysis_planner import AnalyzedSystemPlan, plan_analyzed_system
from .analyzed_discovery_v2 import AnalyzedDiscoveryV2, analyze_declared_components_v2
from .axi_lite import (
    AXI_LITE_STATE_TABLE,
    AxiLiteCycle,
    AxiLiteFabricConfig,
    AxiLiteReferenceModel,
    AxiLiteResponse,
    emit_axi_lite_assertions,
    emit_axi_lite_fabric,
)
from .axi_lite_v4 import (
    AXI_LITE_V4_RULE_IDS,
    AxiLiteGuardedIntent,
    AxiLiteMasterSignals,
    AxiLiteSlaveFeedback,
    AxiLiteV4Capability,
    AxiLiteV4Frontend,
    AxiLiteV4Monitor,
    axi_lite_v4_profile_registry,
    build_axi_lite_v4_layout,
    build_axi_lite_protocol_layout,
    emit_axi_lite_v4_frontend_rtl,
    emit_axi_lite_v4_monitor_rtl,
    pack_axi_lite_protocol_record,
    unpack_axi_lite_protocol_record,
)
from .adaptive_mutation_v4 import (
    AdaptiveMutationController,
    MutationCandidate,
    MutationConfig,
    MutationLevel,
    MutationState,
    ProtocolCampaignPolicy,
    ProtocolLaneScheduler,
    mutation_manifest,
    protocol_campaign_policy,
)
from .master_mutex_v4 import MasterMutexSnapshot, MasterMutexV4, emit_master_mutex_v4_rtl
from .axi_lite_fabric_v4 import (
    AxiLiteFabricV4Capability,
    AxiLiteFabricV4Input,
    AxiLiteFabricV4Model,
    AxiLiteFabricV4Output,
    AxiLiteTargetFeedbackV4,
    emit_axi_lite_fabric_v4,
)
from .apb import ApbDecoderConfig, emit_apb_decoder, emit_axi_lite_to_apb_bridge
from .generated_soc_v2 import EmittedSocIRV2, SocExternalPort, emit_soc_ir_v2
from .generated_soc_v4 import EmittedSocIRV4, emit_soc_ir_v4
from .controller_v4 import (
    AddressBiasConfigV4, ControllerResult, CoverageUnionV4, TargetExecutionResultV4,
    V4Controller, V4TargetServer,
)
from .checkpoint_v4 import CampaignCheckpointStoreV4
from .protocol_campaign_v4 import (
    CoverageProjectionV4, ExternalInfrastructureFailureV4, ProjectedTargetServerV4,
    ProtocolCampaignResultV4,
    ProtocolOnlyExperimentManifestV4, ResourceSnapshotV4,
    SerialProtocolCampaignResultV4, VariantFeasibilityFailureV4,
    build_component_coverage_projection_v4,
    build_protocol_only_experiment_manifest_v4, project_coverage_bitmap_v4,
    run_protocol_campaign_v4,
    run_legacy_a_protocol_campaign_v4, run_serial_protocol_abcd_v4,
    snapshot_resources,
)
from .generated_harness_v4 import EmittedHarnessV4, emit_protocol_harness_v4
from .generated_pipeline_v4 import GeneratedPipelineV4, build_generated_pipeline_v4
from .cpu_semantic_v4 import (
    CpuBootImageV4, CpuExecutionProfile, CpuMemoryRegion, CpuStateDomain,
    ProgramFragmentIR, ProgramLoaderImageV4, build_cpu_semantic_v4_layout,
    build_mmio_smoke_program_fragment_v4, build_rv32i_boot_image_v4,
    cpu_execution_profile_v4_from_dict, cpu_state_domain_v4_from_dict,
    decode_cpu_semantic_payload_v4, decode_program_fragment_records_v4,
    encode_cpu_semantic_payload_v4, encode_program_fragment_records_v4,
    materialize_program_fragment_v4,
    picorv32_semantic_profile, ultra_riscv_semantic_profile,
)
from .generated_harness_v2 import (
    MODE_B_GENERATED_RAW,
    MODE_C_PROTOCOL_SAFE,
    MODE_D_SCENARIO_CONSTRAINED,
    EmittedGeneratedHarnessV2,
    emit_generated_harness_v2,
)
from .graph_diff import (
    EdgeEquivalence, GraphDiff, compare_planned_realized, graph_from_system_ir,
    realized_graph_from_analysis, require_equivalent, verify_realized_system_ir,
)
from .soc_emitter import EmittedSoc, emit_generated_soc_top, emit_soc_filelist
from .soc_ir_v2 import build_soc_ir_v2
from .service_rtl import emit_system_service_target
from .system_services import (
    SystemServicePlan,
    SystemServiceRegion,
    add_system_services_to_soc_ir,
    plan_system_services,
)
from .control_plane import CONTROL_OPCODES, GeneratedControlPlane, build_control_plane
from .control_mailbox import (
    ControlMailboxABI,
    ControlMailboxField,
    build_control_mailbox_abi,
    emit_control_mailbox,
)
from .control_rom import ControlRomArtifact, generate_control_rom
from .interrupt_mapper import emit_interrupt_mapper
from .reset_controller import emit_reset_controller
from .constraint_synthesis import SynthesizedConstraints, synthesize_temporal_constraints
from .register_model import REGISTER_ACCESSES, build_register_model, import_cmsis_svd
from .temporal_v2 import (
    PRIMITIVE_OPERANDS, TEMPORAL_SPECIFICATION_DIGEST, TemporalConstraintEvaluator,
    TemporalStep, build_temporal_constraint_ir_v2,
)
from .temporal_rtl import EmittedTemporalRTL, emit_temporal_constraint_rtl
from .flat_shell import EmittedFlatShell, emit_flat_shell
from .coverage_v2 import (
    build_common_coverage_abi_v2, coverage_abi_v2_digest_payload,
    infer_hierarchy_component_ids, infer_hierarchy_component_paths,
)
from .cpu_profiles import (
    builtin_cpu_execution_profile,
    builtin_cpu_execution_profiles,
    picorv32_execution_profile,
    ultra_riscv_execution_profile,
)
from .level1_rom import Level1IPWindow, Level1RomArtifact, generate_level1_rom
from .formal_ip_set import (
    QualifiedAxiLiteIP, formal_axi_lite_ip_set, formal_ip_windows, validate_formal_ip_sources,
)
from .large_soc import EmittedLargeSoc, emit_large_generated_soc
from .large_soc_constraints import (
    AppliedExternalConstraint, LargeSocExternalContract, build_large_soc_external_contract,
)
from .experiment_inputs import (
    DecodedExperimentSlot, ExperimentInputDecoder, SchemeInputUse, SupersetInputContract,
    build_superset_constraint_ir, build_superset_input_contract,
)
from .large_soc_harness import EmittedLargeSocHarness, emit_large_soc_transaction_harness
from .large_soc_flat import emit_large_flat_soc
from .large_soc_qualification import LargeSocQualification, qualify_large_soc_coverage
from .large_soc_campaign import (
    LargeSocCampaignTargets, build_large_soc_campaign_targets,
    emit_large_flat_campaign_harness, emit_large_generated_campaign_harness,
)
from .rfuzz_campaign import (
    RFuzzCampaignRun, RFuzzConformanceRun, RFuzzGeometry, RFuzzInputTest, RFuzzTargetServer,
    emit_rfuzz_toml,
    encode_rfuzz_coverage_buffer, parse_rfuzz_input_buffer, rfuzz_geometry,
    run_rfuzz_conformance_smoke, run_rfuzz_timed_campaign,
)
from .rawbits import (
    RAWBITS_LAYOUT_SCHEMA, RAWBITS_SCHEMA, RawBitsLayout, RawBitsLayoutEntry,
    RawBitsTestcase, build_rawbits_layout, decode_rawbits_testcase,
    load_rawbits_testcase, pack_rawbits_cycles, write_rawbits_testcase,
)
from .constraint_engine import ConstraintInterpreter, ConstraintPrimitive, build_constraint_ir
from .harness import EmittedHarness, HarnessPort, emit_dual_mode_harness
from .harness_policy import (
    UnknownPortHarnessPlan, UnknownPortModeMapping, map_unknown_ports_to_harness,
)
from .atomic_target import (
    FIXED_CYCLE_RUNNER_SCHEMA, LEGACY_RUNNER_SCHEMA, BuiltTarget, TargetRun,
    build_verilator_target, minimize_rawbits_cycles, rebuild_verilator_target_runner,
    run_verilator_target, write_minimized_rawbits,
)
from .generated_target_v2 import build_generated_verilator_target_v2
from .generated_target_v4 import (
    GeneratedTargetReplayContextV4, GeneratedTargetServerV4,
    build_protocol_verilator_target_v4,
    run_protocol_verilator_target_v4,
)
from .wire_replay_v4 import (
    WireReplayBundleV4, WireReplayEvidenceStoreV4,
    build_wire_replay_bundle_v4, replay_wire_bundle_v4,
    wire_replay_bundle_v4_from_dict,
)
from .environment_v4 import (
    EnvironmentInputBindingV4, EnvironmentInputRuleV4, EnvironmentOutputObservationV4,
    EnvironmentPlanV4, EnvironmentReplayFieldV4, EnvironmentReplayLimitsV4,
    build_environment_plan_v4, decode_environment_replay_v4,
    encode_environment_replay_v4, environment_plan_v4_from_dict,
    validate_environment_replay_v4,
)
from .generated_pipeline_v2 import GeneratedPipelineV2, build_generated_pipeline_v2
from .protocol_pipeline_v2 import ProtocolSystemBuildV2, build_protocol_system_v2
from .protocol_pipeline_v4 import ProtocolSystemBuildV4, build_protocol_system_v4
from .generated_experiment_v2 import (
    GENERATED_MODES, GeneratedBCDCampaign, GeneratedBCDRun, replay_generated_variant,
    run_generated_bcd_campaign, run_generated_bcd_seed,
)
from .abcd_campaign_v2 import coverage_point_catalog, run_abcd_campaign
from .rawbits_v3 import RawBitsV3Field, RawBitsV3Layout, build_rawbits_v3_layout
from .rawbits_v4 import (
    RawBitsV4Lane, RawBitsV4Limits, RawBitsV4Submode, RawBitsV4Layout,
    build_rawbits_v4_layout, encode_rawbits_v4_testcase, decode_rawbits_v4_testcase,
    rawbits_v4_layout_from_dict,
)
from .rawbits_v5 import (
    RAWBITS_V5_LAYOUT_SCHEMA,
    RAWBITS_V5_MAX_STEPS,
    RAWBITS_V5_MAX_TESTCASE_BYTES,
    RawBitsV5Field,
    RawBitsV5Layout,
    RawBitsV5Run,
    RawBitsV5Testcase,
    build_rawbits_v5_layout,
    decode_rawbits_v5_record,
    decode_rawbits_v5_testcase,
    encode_rawbits_v5_records,
    rawbits_v5_layout_from_dict,
    run_rawbits_v5_reference,
)
from .qualification import (
    ACCEPTANCE_SCHEMA, ORACLE_SCHEMA, QualificationOracle, compute_oracle_digest,
    evaluate_acceptance, load_qualification_oracle,
)
from .rtl_analysis import (
    AnalysisLimitation,
    Evidence,
    EvidenceState,
    FRONTEND_SUPPORT_MATRIX,
    RTLAnalysis,
    RTLInstance,
    RTLMemory,
    RTLModule,
    RTLPinBinding,
    RTLPort,
    SignalDependency,
    analyze_elaboration, analyze_elaboration_with_frontend,
)
from .compose_v5 import (
    COMPOSE_V5_MANIFEST_SCHEMA,
    COMPOSE_V5_QUALIFICATION_SCHEMA,
    COMPOSE_V5_TARGET_AUDIT_SCHEMA,
    ComposeV5Component,
    ComposeV5ComponentQualification,
    ComposeV5Failure,
    ComposeV5Manifest,
    ComposeV5Qualification,
    ComposeV5Role,
    ComposeV5SourceSet,
    ComposeV5TargetAudit,
    ComposeV5TargetResult,
    audit_compose_v5_targets,
    compose_v5_manifest_from_dict,
    load_compose_v5_manifest,
    qualify_compose_v5_manifest,
    write_compose_v5_json,
)
from .contract_v5 import (
    CONTRACT_V5_AMBIGUITY_SCHEMA,
    CONTRACT_V5_CANONICAL_SCHEMA,
    CONTRACT_V5_GRAMMAR_VERSION,
    CONTRACT_V5_DIRECTIONS,
    CONTRACT_V5_ORDERING_RELATIONS,
    CONTRACT_V5_POLARITIES,
    CONTRACT_V5_PREDICATE_KINDS,
    CONTRACT_V5_SIGNAL_ROLES,
    ContractV5AmbiguityReport,
    ContractV5CanonicalHypothesis,
    ContractV5Event,
    ContractV5Hypothesis,
    ContractV5Ordering,
    ContractV5Predicate,
    ContractV5SignalRef,
    classify_contract_v5_ambiguity,
    canonicalize_contract_v5_hypothesis,
    contract_v5_hypothesis_digest,
)
from .frontend_v5 import (
    FRONTEND_BEHAVIOR_SCHEMA,
    FrontendV5Behavior,
    FrontendV5Expression,
    FrontendV5Guard,
    FrontendV5ModuleBehavior,
    FrontendV5Process,
    FrontendV5Sensitivity,
    FrontendV5Transition,
    extract_frontend_v5_behavior,
)

__all__ = [
    "AddressMode",
    "AddressRequest",
    "ClockDomain",
    "InterfaceSpec",
    "InputValidationError",
    "ModuleKind",
    "ModuleSpec",
    "PortAnnotation",
    "PortDirection",
    "ResetDomain",
    "SourceSet",
    "SystemSpec",
    "UnknownPortPolicySpec",
    "load_system_spec",
    "InterfaceRole",
    "ChannelRule",
    "MatchSource",
    "PortResolution",
    "PortRule",
    "ProfileAddressRule",
    "ProfileRegistry",
    "ProtocolProfile",
    "builtin_profile_registry",
    "BackendRegistry",
    "BackendSpec",
    "CapabilityMismatch",
    "builtin_backend_registry",
    "ModuleClassification",
    "classify_modules",
    "InterfaceBinding",
    "PortBinding",
    "SystemPlan",
    "plan_system",
    "emit_system",
    "emit_rfuzz_metadata",
    "generate_rfuzz_testcase",
    "run_instrumentation",
    "run_soc_instrumentation",
    "update_generation_report",
    "DecisionStatus",
    "UnknownInputRequest",
    "UnknownPortAction",
    "UnknownPortDecision",
    "decide_unknown_port",
    "unknown_port_report",
    "AddressIntent",
    "AddressPlan",
    "AddressPlanEntry",
    "AddressWindow",
    "allocate_addresses",
    "ConnectionEdge",
    "ConnectionKind",
    "ConnectionRequest",
    "ConstraintKind",
    "EndpointRef",
    "SignalConstraint",
    "SignalEndpoint",
    "SystemGraph",
    "build_system_graph",
    "DiscoveredInstance",
    "DiscoveredModule",
    "DiscoveredPort",
    "DiscoveryResult",
    "discover_system",
    "AnalyzedSystemPlan",
    "plan_analyzed_system",
    "AnalyzedDiscoveryV2",
    "analyze_declared_components_v2",
    "AxiLiteCycle",
    "AXI_LITE_STATE_TABLE",
    "AxiLiteFabricConfig",
    "AxiLiteReferenceModel",
    "AxiLiteResponse",
    "emit_axi_lite_fabric",
    "emit_axi_lite_assertions",
    "ApbDecoderConfig",
    "emit_apb_decoder",
    "emit_axi_lite_to_apb_bridge",
    "EmittedSocIRV2",
    "SocExternalPort",
    "emit_soc_ir_v2",
    "EmittedSocIRV4",
    "emit_soc_ir_v4",
    "ControllerResult",
    "AddressBiasConfigV4",
    "CoverageUnionV4",
    "TargetExecutionResultV4",
    "V4Controller",
    "V4TargetServer",
    "CampaignCheckpointStoreV4",
    "CoverageProjectionV4",
    "ProjectedTargetServerV4",
    "ProtocolCampaignResultV4",
    "ProtocolOnlyExperimentManifestV4",
    "ResourceSnapshotV4",
    "SerialProtocolCampaignResultV4",
    "VariantFeasibilityFailureV4",
    "ExternalInfrastructureFailureV4",
    "build_component_coverage_projection_v4",
    "build_protocol_only_experiment_manifest_v4",
    "project_coverage_bitmap_v4",
    "run_legacy_a_protocol_campaign_v4",
    "run_protocol_campaign_v4",
    "run_serial_protocol_abcd_v4",
    "snapshot_resources",
    "EmittedHarnessV4",
    "emit_protocol_harness_v4",
    "GeneratedPipelineV4",
    "build_generated_pipeline_v4",
    "CpuExecutionProfile",
    "CpuBootImageV4",
    "CpuMemoryRegion",
    "CpuStateDomain",
    "ProgramFragmentIR",
    "build_mmio_smoke_program_fragment_v4",
    "ProgramLoaderImageV4",
    "build_cpu_semantic_v4_layout",
    "build_rv32i_boot_image_v4",
    "cpu_execution_profile_v4_from_dict",
    "cpu_state_domain_v4_from_dict",
    "decode_cpu_semantic_payload_v4",
    "decode_program_fragment_records_v4",
    "encode_cpu_semantic_payload_v4",
    "encode_program_fragment_records_v4",
    "materialize_program_fragment_v4",
    "picorv32_semantic_profile",
    "ultra_riscv_semantic_profile",
    "MODE_B_GENERATED_RAW",
    "MODE_C_PROTOCOL_SAFE",
    "MODE_D_SCENARIO_CONSTRAINED",
    "EmittedGeneratedHarnessV2",
    "emit_generated_harness_v2",
    "EdgeEquivalence",
    "GraphDiff",
    "compare_planned_realized",
    "graph_from_system_ir",
    "realized_graph_from_analysis",
    "require_equivalent",
    "verify_realized_system_ir",
    "EmittedSoc",
    "emit_generated_soc_top",
    "emit_soc_filelist",
    "build_soc_ir_v2",
    "emit_system_service_target",
    "SystemServicePlan",
    "SystemServiceRegion",
    "plan_system_services",
    "add_system_services_to_soc_ir",
    "CONTROL_OPCODES",
    "ControlMailboxABI",
    "ControlMailboxField",
    "build_control_mailbox_abi",
    "emit_control_mailbox",
    "ControlRomArtifact",
    "generate_control_rom",
    "emit_interrupt_mapper",
    "emit_reset_controller",
    "SynthesizedConstraints",
    "synthesize_temporal_constraints",
    "GeneratedControlPlane",
    "build_control_plane",
    "REGISTER_ACCESSES",
    "build_register_model",
    "import_cmsis_svd",
    "PRIMITIVE_OPERANDS",
    "TEMPORAL_SPECIFICATION_DIGEST",
    "TemporalConstraintEvaluator",
    "TemporalStep",
    "build_temporal_constraint_ir_v2",
    "EmittedTemporalRTL",
    "emit_temporal_constraint_rtl",
    "EmittedFlatShell",
    "emit_flat_shell",
    "build_common_coverage_abi_v2",
    "infer_hierarchy_component_ids",
    "infer_hierarchy_component_paths",
    "coverage_abi_v2_digest_payload",
    "builtin_cpu_execution_profile",
    "builtin_cpu_execution_profiles",
    "picorv32_execution_profile",
    "ultra_riscv_execution_profile",
    "Level1IPWindow",
    "Level1RomArtifact",
    "generate_level1_rom",
    "QualifiedAxiLiteIP",
    "formal_axi_lite_ip_set",
    "formal_ip_windows",
    "validate_formal_ip_sources",
    "EmittedLargeSoc",
    "emit_large_generated_soc",
    "AppliedExternalConstraint",
    "LargeSocExternalContract",
    "build_large_soc_external_contract",
    "DecodedExperimentSlot",
    "ExperimentInputDecoder",
    "SchemeInputUse",
    "SupersetInputContract",
    "build_superset_input_contract",
    "build_superset_constraint_ir",
    "EmittedLargeSocHarness",
    "emit_large_soc_transaction_harness",
    "LargeSocQualification",
    "qualify_large_soc_coverage",
    "emit_large_flat_campaign_harness",
    "emit_large_generated_campaign_harness",
    "LargeSocCampaignTargets",
    "build_large_soc_campaign_targets",
    "RFuzzCampaignRun",
    "RFuzzConformanceRun",
    "run_rfuzz_conformance_smoke",
    "run_rfuzz_timed_campaign",
    "emit_large_flat_soc",
    "RAWBITS_LAYOUT_SCHEMA",
    "RAWBITS_SCHEMA",
    "RawBitsLayout",
    "RawBitsLayoutEntry",
    "RawBitsTestcase",
    "build_rawbits_layout",
    "decode_rawbits_testcase",
    "load_rawbits_testcase",
    "pack_rawbits_cycles",
    "write_rawbits_testcase",
    "ConstraintInterpreter",
    "ConstraintPrimitive",
    "build_constraint_ir",
    "EmittedHarness",
    "HarnessPort",
    "emit_dual_mode_harness",
    "UnknownPortHarnessPlan",
    "UnknownPortModeMapping",
    "map_unknown_ports_to_harness",
    "BuiltTarget",
    "TargetRun",
    "LEGACY_RUNNER_SCHEMA",
    "FIXED_CYCLE_RUNNER_SCHEMA",
    "build_verilator_target",
    "rebuild_verilator_target_runner",
    "run_verilator_target",
    "minimize_rawbits_cycles",
    "write_minimized_rawbits",
    "build_generated_verilator_target_v2",
    "build_protocol_verilator_target_v4",
    "GeneratedTargetServerV4",
    "run_protocol_verilator_target_v4",
    "WireReplayBundleV4",
    "build_wire_replay_bundle_v4",
    "replay_wire_bundle_v4",
    "wire_replay_bundle_v4_from_dict",
    "EnvironmentInputBindingV4",
    "EnvironmentInputRuleV4",
    "EnvironmentOutputObservationV4",
    "EnvironmentPlanV4",
    "EnvironmentReplayFieldV4",
    "EnvironmentReplayLimitsV4",
    "build_environment_plan_v4",
    "decode_environment_replay_v4",
    "encode_environment_replay_v4",
    "environment_plan_v4_from_dict",
    "validate_environment_replay_v4",
    "GeneratedPipelineV2",
    "build_generated_pipeline_v2",
    "ProtocolSystemBuildV2",
    "build_protocol_system_v2",
    "ProtocolSystemBuildV4",
    "build_protocol_system_v4",
    "GENERATED_MODES",
    "GeneratedBCDRun",
    "GeneratedBCDCampaign",
    "coverage_point_catalog",
    "run_abcd_campaign",
    "AXI_LITE_V4_RULE_IDS",
    "AxiLiteGuardedIntent",
    "AxiLiteMasterSignals",
    "AxiLiteSlaveFeedback",
    "AxiLiteV4Capability",
    "AxiLiteV4Frontend",
    "AxiLiteV4Monitor",
    "axi_lite_v4_profile_registry",
    "build_axi_lite_v4_layout",
    "build_axi_lite_protocol_layout",
    "emit_axi_lite_v4_frontend_rtl",
    "emit_axi_lite_v4_monitor_rtl",
    "pack_axi_lite_protocol_record",
    "unpack_axi_lite_protocol_record",
    "AdaptiveMutationController",
    "MutationCandidate",
    "MutationConfig",
    "MutationLevel",
    "MutationState",
    "ProtocolCampaignPolicy",
    "ProtocolLaneScheduler",
    "mutation_manifest",
    "protocol_campaign_policy",
    "MasterMutexSnapshot",
    "MasterMutexV4",
    "emit_master_mutex_v4_rtl",
    "AxiLiteFabricV4Capability",
    "AxiLiteFabricV4Input",
    "AxiLiteFabricV4Model",
    "AxiLiteFabricV4Output",
    "AxiLiteTargetFeedbackV4",
    "emit_axi_lite_fabric_v4",
    "run_generated_bcd_seed",
    "run_generated_bcd_campaign",
    "replay_generated_variant",
    "RawBitsV3Field",
    "RawBitsV3Layout",
    "build_rawbits_v3_layout",
    "RawBitsV4Lane",
    "RawBitsV4Limits",
    "RawBitsV4Submode",
    "RawBitsV4Layout",
    "build_rawbits_v4_layout",
    "encode_rawbits_v4_testcase",
    "decode_rawbits_v4_testcase",
    "rawbits_v4_layout_from_dict",
    "ORACLE_SCHEMA",
    "ACCEPTANCE_SCHEMA",
    "QualificationOracle",
    "compute_oracle_digest",
    "load_qualification_oracle",
    "evaluate_acceptance",
    "AnalysisLimitation",
    "Evidence",
    "EvidenceState",
    "FRONTEND_SUPPORT_MATRIX",
    "RTLAnalysis",
    "RTLInstance",
    "RTLMemory",
    "RTLModule",
    "RTLPinBinding",
    "RTLPort",
    "SignalDependency",
    "analyze_elaboration",
    "analyze_elaboration_with_frontend",
    "COMPOSE_V5_MANIFEST_SCHEMA",
    "COMPOSE_V5_QUALIFICATION_SCHEMA",
    "COMPOSE_V5_TARGET_AUDIT_SCHEMA",
    "ComposeV5Component",
    "ComposeV5ComponentQualification",
    "ComposeV5Failure",
    "ComposeV5Manifest",
    "ComposeV5Qualification",
    "ComposeV5Role",
    "ComposeV5SourceSet",
    "ComposeV5TargetAudit",
    "ComposeV5TargetResult",
    "audit_compose_v5_targets",
    "compose_v5_manifest_from_dict",
    "load_compose_v5_manifest",
    "qualify_compose_v5_manifest",
    "write_compose_v5_json",
    "CONTRACT_V5_GRAMMAR_VERSION",
    "CONTRACT_V5_CANONICAL_SCHEMA",
    "CONTRACT_V5_AMBIGUITY_SCHEMA",
    "CONTRACT_V5_DIRECTIONS",
    "CONTRACT_V5_POLARITIES",
    "CONTRACT_V5_SIGNAL_ROLES",
    "CONTRACT_V5_PREDICATE_KINDS",
    "CONTRACT_V5_ORDERING_RELATIONS",
    "ContractV5SignalRef",
    "ContractV5Predicate",
    "ContractV5Event",
    "ContractV5Ordering",
    "ContractV5Hypothesis",
    "ContractV5CanonicalHypothesis",
    "ContractV5AmbiguityReport",
    "canonicalize_contract_v5_hypothesis",
    "contract_v5_hypothesis_digest",
    "classify_contract_v5_ambiguity",
    "RAWBITS_V5_LAYOUT_SCHEMA",
    "RAWBITS_V5_MAX_STEPS",
    "RAWBITS_V5_MAX_TESTCASE_BYTES",
    "RawBitsV5Field",
    "RawBitsV5Layout",
    "RawBitsV5Run",
    "RawBitsV5Testcase",
    "build_rawbits_v5_layout",
    "decode_rawbits_v5_record",
    "decode_rawbits_v5_testcase",
    "encode_rawbits_v5_records",
    "rawbits_v5_layout_from_dict",
    "run_rawbits_v5_reference",
    "FRONTEND_BEHAVIOR_SCHEMA",
    "FrontendV5Behavior",
    "FrontendV5Expression",
    "FrontendV5Guard",
    "FrontendV5ModuleBehavior",
    "FrontendV5Process",
    "FrontendV5Sensitivity",
    "FrontendV5Transition",
    "extract_frontend_v5_behavior",
]
