+incdir+external_designs/opentitan/hw/ip/lc_ctrl/rtl
+incdir+external_designs/opentitan/hw/ip/prim/rtl
+incdir+external_designs/opentitan/hw/ip/prim_generic/rtl
+incdir+external_designs/opentitan/hw/ip/rv_dm/rtl
+incdir+external_designs/opentitan/hw/ip/rv_timer/rtl
+incdir+external_designs/opentitan/hw/ip/tlul/rtl
+incdir+external_designs/opentitan/hw/ip/uart/rtl
+incdir+external_designs/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl
+incdir+external_designs/opentitan/hw/top_earlgrey/rtl
+incdir+external_designs/opentitan/hw/top_earlgrey/rtl/autogen
+incdir+external_designs/opentitan/hw/vendor/pulp_riscv_dbg/debug_rom
+incdir+external_designs/opentitan/hw/vendor/pulp_riscv_dbg/src
external_designs/opentitan/hw/top_earlgrey/rtl/top_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_util_pkg.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_flop.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_cdc_rand_delay.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_flop_2sync.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_xnor2.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_diff_decode.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_pad_wrapper_pkg.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_pad_wrapper.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_clock_mux2.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_clock_inv.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_const.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_const_sec.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_buf.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sec_anchor_buf.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sec_anchor_const.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sec_anchor_flop.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_flop_en.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_flop_no_rst.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi4_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi4_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi4_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi8_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi8_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi8_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi12_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi12_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi12_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi16_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi16_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi16_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi20_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi20_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi20_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi24_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi24_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi24_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi28_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi28_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi28_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi32_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi32_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_mubi32_dec.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_rst_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_leading_one_ppc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_arbiter_fixed.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_arbiter_ppc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_arbiter_tree.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_arbiter_tree_dup.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_count_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_count.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_fifo_async_simple.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_fifo_async.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_fifo_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_22_16_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_22_16_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_28_22_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_28_22_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_39_32_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_39_32_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_64_57_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_64_57_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_72_64_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_72_64_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_hamming_76_68_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_hamming_76_68_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_22_16_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_22_16_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_enc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_dec.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_enc.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_pkg.sv
external_designs/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
external_designs/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
external_designs/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_alert_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_alert_receiver.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_alert_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_esc_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_esc_receiver.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_esc_sender.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_subreg_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_reg_cdc.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_reg_cdc_arb.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_subreg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_subreg_arb.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_subreg_ext.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_subreg_shadow.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_cipher_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_subst_perm.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_present.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_prince.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_xor2.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_and2.sv
external_designs/opentitan/hw/ip/prim_generic/rtl/prim_inv.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_onehot_check.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_reg_we_check.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sha2_pkg.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sha2_pad.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sha2.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sha2_32.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_clock_gating_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_hpc2.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_hpc3.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sram_arbiter.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_slicer.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sync_reqack.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sync_reqack_data.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sync_slow_fast.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_keccak.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_packer.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_packer_fifo.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_gate_gen.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_pulse_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_filter.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_filter_ctr.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_flop_x.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_intr_hw.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_data_integ_enc.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_data_integ_dec.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_chk.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_fifo_sync.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_fifo_async.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_assert.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_err.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_assert_multiple.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_err_resp.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_socket_1n.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_socket_m1.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_sram_byte.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_adapter_sram.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_request_loopback.sv
external_designs/opentitan/hw/top_earlgrey/rtl/autogen/top_racl_pkg.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_adapter_racl.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_adapter_reg.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom_one_scratch.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_pkg.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_sba.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_csrs.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_mem.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/src/dmi_cdc.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/src/dmi_jtag.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/src/dmi_jtag_tap.sv
external_designs/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_top.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_adapter_dmi.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_adapter_host.sv
external_designs/opentitan/hw/ip/rv_dm/rtl/jtag_pkg.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_jtag_dtm.sv
external_designs/opentitan/hw/ip/tlul/rtl/sram2tlul.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_blanker.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_lc_sync.sv
external_designs/opentitan/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
external_designs/opentitan/hw/ip/tlul/rtl/tlul_lc_gate.sv
external_designs/opentitan/hw/ip/uart/rtl/uart_reg_pkg.sv
external_designs/opentitan/hw/ip/uart/rtl/uart_reg_top.sv
external_designs/opentitan/hw/ip/uart/rtl/uart_rx.sv
external_designs/opentitan/hw/ip/uart/rtl/uart_tx.sv
external_designs/opentitan/hw/ip/uart/rtl/uart_core.sv
external_designs/opentitan/hw/ip/uart/rtl/uart.sv
external_designs/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_pkg.sv
external_designs/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_reg_pkg.sv
external_designs/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_reg_top.sv
external_designs/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio.sv
external_designs/opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_pkg.sv
external_designs/opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_top.sv
external_designs/opentitan/hw/ip/rv_timer/rtl/timer_core.sv
external_designs/opentitan/hw/ip/rv_timer/rtl/rv_timer.sv
