#!/usr/bin/env python3
"""Prepare remote Ibex + common-IP filelists/configs.

Run this on inner70 from /root/fanzehui/myfuzz before RFuzz stages.  The local
workspace does not contain third_party/rfuzz/upstream/ibex, so this script is
intentionally remote-oriented.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


LOCAL_RTL = [
    "configs/designs/ibex_multicomponent_ip/rtl/ibex_mcip_ram.sv",
    "configs/designs/ibex_multicomponent_ip/rtl/ibex_mcip_timer.sv",
    "configs/designs/ibex_multicomponent_ip/rtl/ibex_mcip_gpio.sv",
    "configs/designs/ibex_multicomponent_ip/rtl/ibex_mcip_uart.sv",
    "configs/designs/ibex_multicomponent_ip/rtl/ibex_mcip_spi.sv",
    "configs/designs/ibex_multicomponent_ip/rtl/ibex_multicomponent_ip_top.sv",
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def strip_line_comment(line: str) -> str:
    idx = line.find("//")
    return line if idx < 0 else line[:idx]


def expand(raw: str, base: Path) -> Path:
    path = Path(raw).expanduser()
    if not path.is_absolute():
        path = base / path
    return path.resolve()


def flatten_flist(path: Path, seen: set[Path] | None = None) -> list[str]:
    if seen is None:
        seen = set()
    path = path.resolve()
    if path in seen:
        return []
    seen.add(path)

    lines: list[str] = []
    base = path.parent
    for raw in path.read_text(errors="ignore").splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        line = strip_line_comment(raw).strip()
        if not line:
            continue
        if line.startswith("-f "):
            lines.extend(flatten_flist(expand(line[3:].strip(), base), seen))
            continue
        if line.startswith("-F "):
            lines.extend(flatten_flist(expand(line[3:].strip(), base), seen))
            continue
        if line.startswith("+incdir+"):
            incdirs = [expand(item, base).as_posix() for item in line[len("+incdir+") :].split("+") if item]
            lines.append("+incdir+" + "+".join(incdirs))
            continue
        if line.startswith("-I") and len(line) > 2:
            lines.append("-I" + expand(line[2:].strip(), base).as_posix())
            continue
        first = line.split()[0]
        candidate = expand(first, base)
        if candidate.suffix.lower() in {".sv", ".v", ".svh", ".vh"} and candidate.exists():
            rest = line[len(first):]
            lines.append(candidate.as_posix() + rest)
        else:
            lines.append(raw)
    return lines


def prepare_filelist(root: Path) -> Path:
    ibex_flist = root / "third_party/rfuzz/upstream/ibex/sources.f"
    if not ibex_flist.exists():
        raise FileNotFoundError(
            f"missing remote Ibex filelist: {ibex_flist}. Run this on inner70 after syncing the repo."
        )

    out = root / "configs/designs/ibex_multicomponent_ip/rtl/generated_remote_sources.f"
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by configs/designs/ibex_multicomponent_ip/scripts/prepare_remote_sources.py",
        "# Ibex upstream sources:",
        *flatten_flist(ibex_flist),
        "",
        "# Local Ibex + common-IP wrapper sources:",
        *[(root / item).as_posix() for item in LOCAL_RTL],
        "",
    ]
    out.write_text("\n".join(lines))
    return out


def add_macro(args: list[str], macro: str) -> list[str]:
    return [item for item in args if not item.startswith("-DIBEX_MCIP_COVERAGE_MSB=")] + [macro]


def coverage_width(root: Path, config_path: Path) -> int:
    cfg = json.loads(config_path.read_text())
    inst = root / cfg["out_dir"] / "instrumented" / "instrumentation.json"
    data = json.loads(inst.read_text())
    for item in data.get("module_coverage", []):
        if item.get("module") == cfg["top"] and item.get("active"):
            return int(item["coverage_width"])
    return int(data["coverage_point_count"])


def write_width_config(root: Path, config_path: Path, width: int) -> Path:
    cfg = json.loads(config_path.read_text())
    args = list(cfg.get("verilator_args", []))
    cfg["verilator_args"] = add_macro(args, f"-DIBEX_MCIP_COVERAGE_MSB={width - 1}")
    out = config_path.with_name("config.coverage_width.json")
    out.write_text(json.dumps(cfg, indent=2) + "\n")
    rel = out.resolve().relative_to(root.resolve())
    return rel


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write-width-config",
        action="append",
        default=[],
        help=(
            "Config path whose out_dir already contains instrumented/instrumentation.json; "
            "writes config.coverage_width.json next to it with the coverage macro."
        ),
    )
    args = parser.parse_args()

    root = repo_root()
    filelist = prepare_filelist(root)
    print(f"wrote {filelist.relative_to(root)}")

    for raw in args.write_width_config:
        cfg_path = (root / raw).resolve()
        width = coverage_width(root, cfg_path)
        rel = write_width_config(root, cfg_path, width)
        print(f"wrote {rel} with IBEX_MCIP_COVERAGE_MSB={width - 1}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
