"""Name-independent declarative composition primitives."""

from .auto import (
    AutoCompositionError,
    AutoCompositionPlan,
    AutoCompositionRequest,
    GenericCompositionPlan,
    GenericCompositionRequest,
    plan_auto_composition,
    plan_generic_composition,
    write_auto_composition_manifest,
)
from .declarations import DeclarationError, DeclarationSet, load_declarations
from .endpoint_capabilities import (
    AdapterCapability,
    EndpointCapability,
    EndpointCapabilityError,
    EndpointFieldFact,
    SourceReference,
    TimingFact,
    match_endpoint_pair,
    normalize_annotations,
    validate_protocol_fingerprint,
)
from .facts import HdlFacts, normalize_facts
from .interface_description import (
    ElaborationSettings,
    EndpointDescription,
    FieldHint,
    PhysicalSelector,
    RepositoryPin,
    InterfaceDescription,
    SourceLocator,
    interface_description_document,
    load_interface_description,
)
from .source_crawler import (
    ElaboratedMemberFact,
    ElaboratedPortFact,
    SourceCrawler,
    SourceCrawlError,
    SourcePortFact,
    SourceSnapshot,
    TimingObservation,
    annotate_interfaces,
    source_tree_hash,
)
from .ids import canonical_id
from .input_layout import InputLayout, InputLayoutError, LayoutField, build_input_layout, input_layout_document
from .ir import composition_ir
from .manifest import candidate_manifest
from .protocol_composer import (
    CompositionArtifact,
    compose_protocol_composition,
    write_generic_composition,
    write_protocol_composition,
)
from .protocol_manifest import (
    CompositionComponent,
    ProtocolCompositionError,
    ProtocolCompositionManifest,
    load_protocol_composition,
    validate_protocol_composition,
)
from .processor_boundary import (
    PackedInputContainer,
    ProcessorBoundary,
    ProcessorBoundaryError,
    ProcessorControlBinding,
    ProcessorMemoryBinding,
    build_processor_boundary,
    processor_boundary_document,
)
from .processor_adapters import (
    ExtensionPolicy,
    ProcessorAdapterDefinition,
    ProcessorAdapterError,
    resolve_processor_adapter,
)
from .processor_execution import (
    ProcessorExecutionError,
    ProcessorExecutionPlan,
    ProcessorExecutionRoute,
    build_processor_execution,
    processor_execution_document,
)
from .processor_backend import (
    ProcessorBackendError,
    ProcessorBackendPlan,
    build_processor_backend,
    processor_backend_document,
)
from .registry import ComponentRegistration, ComponentRegistry, default_component_registry
from .search import CompositionCandidate, compose_topk

__all__ = [
    "AutoCompositionError",
    "AutoCompositionPlan",
    "AutoCompositionRequest",
    "GenericCompositionPlan",
    "GenericCompositionRequest",
    "AdapterCapability",
    "DeclarationError",
    "DeclarationSet",
    "HdlFacts",
    "EndpointDescription",
    "ElaborationSettings",
    "ExtensionPolicy",
    "ElaboratedMemberFact",
    "ElaboratedPortFact",
    "EndpointCapability",
    "EndpointCapabilityError",
    "EndpointFieldFact",
    "SourceReference",
    "TimingFact",
    "FieldHint",
    "PhysicalSelector",
    "RepositoryPin",
    "InterfaceDescription",
    "InputLayout",
    "InputLayoutError",
    "LayoutField",
    "SourceLocator",
    "SourceCrawler",
    "SourceCrawlError",
    "SourcePortFact",
    "SourceSnapshot",
    "TimingObservation",
    "CompositionCandidate",
    "CompositionArtifact",
    "CompositionComponent",
    "ComponentRegistration",
    "ComponentRegistry",
    "ProtocolCompositionError",
    "ProtocolCompositionManifest",
    "PackedInputContainer",
    "ProcessorBoundary",
    "ProcessorBoundaryError",
    "ProcessorAdapterDefinition",
    "ProcessorAdapterError",
    "ProcessorControlBinding",
    "ProcessorMemoryBinding",
    "ProcessorExecutionError",
    "ProcessorExecutionPlan",
    "ProcessorExecutionRoute",
    "ProcessorBackendError",
    "ProcessorBackendPlan",
    "candidate_manifest",
    "build_input_layout",
    "build_processor_execution",
    "build_processor_backend",
    "build_processor_boundary",
    "annotate_interfaces",
    "canonical_id",
    "compose_topk",
    "compose_protocol_composition",
    "composition_ir",
    "default_component_registry",
    "interface_description_document",
    "input_layout_document",
    "load_declarations",
    "load_interface_description",
    "match_endpoint_pair",
    "normalize_annotations",
    "load_protocol_composition",
    "normalize_facts",
    "plan_auto_composition",
    "plan_generic_composition",
    "processor_boundary_document",
    "resolve_processor_adapter",
    "processor_execution_document",
    "processor_backend_document",
    "source_tree_hash",
    "validate_protocol_composition",
    "validate_protocol_fingerprint",
    "write_protocol_composition",
    "write_generic_composition",
    "write_auto_composition_manifest",
]
