// Non-frontend Verilator service stubs used by the myfuzz frontend component.

#define VL_MT_CONTROL_CODE_UNIT 1

#include "V3Ast.h"
#include "V3DiagSarif.h"
#include "V3EmitCBase.h"
#include "V3EmitV.h"
#include "V3File.h"
#include "V3Stats.h"
#include "V3Waiver.h"

#include <fstream>
#include <sstream>

V3Mutex V3Stats::s_mutex;
V3Mutex V3Waiver::s_mutex;
std::vector<std::string> V3Waiver::s_waiverList;

void V3Statistic::dump(std::ofstream& os) const {
    os << value();
}

void V3Stats::addStat(const V3Statistic&) {}
double V3Stats::getStatSum(const string&) { return 0.0; }
void V3Stats::statsStage(const string&) {}
void V3Stats::statsStageAll(AstNetlist*, const string&, bool) {}
void V3Stats::statsFinalAll(AstNetlist*) {}
void V3Stats::statsReport() {}
void V3Stats::summaryReport() {}
void V3Stats::infoHeader(std::ofstream& os, const string& prefix) {
    os << prefix << "Generated by myfuzz frontend\n";
}

void V3DiagSarif::pushMessage(const VErrorMessage&) {}
void V3DiagSarif::output(bool) {}

void V3Waiver::addEntry(V3ErrorCode, const string&, const std::string&) {}
void V3Waiver::write(const std::string&) {}

string EmitCUtil::prefixNameProtect(const AstNode* nodep) {
    return nodep ? VIdProtect::protect(nodep->name()) : "";
}

EmitCParentModule::EmitCParentModule() = default;

string EmitCBaseVisitorConst::funcNameProtect(const AstCFunc* nodep, const AstNodeModule*) {
    return nodep ? VIdProtect::protect(nodep->name()) : "";
}

string EmitCBaseVisitorConst::cFuncArgs(const AstCFunc*) { return ""; }
void EmitCBaseVisitorConst::emitCDefaultConstructor(const AstNodeModule*) {}
void EmitCBaseVisitorConst::emitCFuncHeader(const AstCFunc*, const AstNodeModule*, bool) {}
void EmitCBaseVisitorConst::emitCFuncDecl(const AstCFunc*, const AstNodeModule*, bool) {}
void EmitCBaseVisitorConst::emitVarDecl(const AstVar*, bool) {}
void EmitCBaseVisitorConst::emitVarAccessors(const AstVar*) {}
void EmitCBaseVisitorConst::emitModCUse(const AstNodeModule*, VUseType) {}
void EmitCBaseVisitorConst::emitSystemCSection(const AstNodeModule*, VSystemCSectionType) {}
std::pair<string, FileLine*> EmitCBaseVisitorConst::scSection(const AstNodeModule*,
                                                              VSystemCSectionType) {
    return {"", nullptr};
}

void V3EmitV::verilogForTree(const AstNode* nodep, std::ostream& os) {
    if (!nodep) return;
    os << nodep->prettyTypeName() << ":" << nodep->prettyName();
}

void V3EmitV::debugVerilogForTree(const AstNode* nodep, std::ostream& os) {
    verilogForTree(nodep, os);
}

std::string V3EmitV::debugVerilogForTree(const AstNode* nodep) {
    std::ostringstream os;
    verilogForTree(nodep, os);
    return os.str();
}

void V3EmitV::emitvFiles() {}
void V3EmitV::debugEmitV(const string&) {}
