// SPDX-License-Identifier: BSD-3-Clause
// Port-only qualification wrapper around upstream riscv_tcm_top.
// The upstream AXI target port is an external TCM loader and is held idle.
module ultra_riscv_axil_cpu_wrapper (
  input  wire        clk,
  input  wire        reset,
  input  wire [31:0] fuzz_irq,
  output wire        m_awvalid,
  input  wire        m_awready,
  output wire [31:0] m_awaddr,
  output wire        m_wvalid,
  input  wire        m_wready,
  output wire [31:0] m_wdata,
  output wire [3:0]  m_wstrb,
  input  wire        m_bvalid,
  output wire        m_bready,
  input  wire [1:0]  m_bresp,
  output wire        m_arvalid,
  input  wire        m_arready,
  output wire [31:0] m_araddr,
  input  wire        m_rvalid,
  output wire        m_rready,
  input  wire [31:0] m_rdata,
  input  wire [1:0]  m_rresp
);
  riscv_tcm_top i_cpu (
    .clk_i(clk),
    .rst_i(reset),
    .rst_cpu_i(reset),
    .axi_i_awready_i(m_awready),
    .axi_i_wready_i(m_wready),
    .axi_i_bvalid_i(m_bvalid),
    .axi_i_bresp_i(m_bresp),
    .axi_i_arready_i(m_arready),
    .axi_i_rvalid_i(m_rvalid),
    .axi_i_rdata_i(m_rdata),
    .axi_i_rresp_i(m_rresp),
    .axi_t_awvalid_i(1'b0),
    .axi_t_awaddr_i(32'b0),
    .axi_t_awid_i(4'b0),
    .axi_t_awlen_i(8'b0),
    .axi_t_awburst_i(2'b0),
    .axi_t_wvalid_i(1'b0),
    .axi_t_wdata_i(32'b0),
    .axi_t_wstrb_i(4'b0),
    .axi_t_wlast_i(1'b0),
    .axi_t_bready_i(1'b0),
    .axi_t_arvalid_i(1'b0),
    .axi_t_araddr_i(32'b0),
    .axi_t_arid_i(4'b0),
    .axi_t_arlen_i(8'b0),
    .axi_t_arburst_i(2'b0),
    .axi_t_rready_i(1'b0),
    .intr_i(fuzz_irq),
    .axi_i_awvalid_o(m_awvalid),
    .axi_i_awaddr_o(m_awaddr),
    .axi_i_wvalid_o(m_wvalid),
    .axi_i_wdata_o(m_wdata),
    .axi_i_wstrb_o(m_wstrb),
    .axi_i_bready_o(m_bready),
    .axi_i_arvalid_o(m_arvalid),
    .axi_i_araddr_o(m_araddr),
    .axi_i_rready_o(m_rready),
    .axi_t_awready_o(),
    .axi_t_wready_o(),
    .axi_t_bvalid_o(),
    .axi_t_bresp_o(),
    .axi_t_bid_o(),
    .axi_t_arready_o(),
    .axi_t_rvalid_o(),
    .axi_t_rdata_o(),
    .axi_t_rresp_o(),
    .axi_t_rid_o(),
    .axi_t_rlast_o()
  );
endmodule
