// SPDX-License-Identifier: MIT
// Expose one port of the upstream dual-port RAM; hold the second port idle.
module verilog_axi_dp_ram_wrapper (
  input  wire        clk,
  input  wire        reset,
  input  wire        s_awvalid,
  output wire        s_awready,
  input  wire [11:0] s_awaddr,
  input  wire        s_wvalid,
  output wire        s_wready,
  input  wire [31:0] s_wdata,
  input  wire [3:0]  s_wstrb,
  output wire        s_bvalid,
  input  wire        s_bready,
  output wire [1:0]  s_bresp,
  input  wire        s_arvalid,
  output wire        s_arready,
  input  wire [11:0] s_araddr,
  output wire        s_rvalid,
  input  wire        s_rready,
  output wire [31:0] s_rdata,
  output wire [1:0]  s_rresp
);
  axil_dp_ram #(
    .DATA_WIDTH(32),
    .ADDR_WIDTH(12)
  ) i_ram (
    .a_clk(clk),
    .a_rst(reset),
    .b_clk(clk),
    .b_rst(reset),
    .s_axil_a_awaddr(s_awaddr),
    .s_axil_a_awprot(3'b000),
    .s_axil_a_awvalid(s_awvalid),
    .s_axil_a_awready(s_awready),
    .s_axil_a_wdata(s_wdata),
    .s_axil_a_wstrb(s_wstrb),
    .s_axil_a_wvalid(s_wvalid),
    .s_axil_a_wready(s_wready),
    .s_axil_a_bresp(s_bresp),
    .s_axil_a_bvalid(s_bvalid),
    .s_axil_a_bready(s_bready),
    .s_axil_a_araddr(s_araddr),
    .s_axil_a_arprot(3'b000),
    .s_axil_a_arvalid(s_arvalid),
    .s_axil_a_arready(s_arready),
    .s_axil_a_rdata(s_rdata),
    .s_axil_a_rresp(s_rresp),
    .s_axil_a_rvalid(s_rvalid),
    .s_axil_a_rready(s_rready),
    .s_axil_b_awaddr(12'b0),
    .s_axil_b_awprot(3'b0),
    .s_axil_b_awvalid(1'b0),
    .s_axil_b_awready(),
    .s_axil_b_wdata(32'b0),
    .s_axil_b_wstrb(4'b0),
    .s_axil_b_wvalid(1'b0),
    .s_axil_b_wready(),
    .s_axil_b_bresp(),
    .s_axil_b_bvalid(),
    .s_axil_b_bready(1'b0),
    .s_axil_b_araddr(12'b0),
    .s_axil_b_arprot(3'b0),
    .s_axil_b_arvalid(1'b0),
    .s_axil_b_arready(),
    .s_axil_b_rdata(),
    .s_axil_b_rresp(),
    .s_axil_b_rvalid(),
    .s_axil_b_rready(1'b0)
  );
endmodule
