"""Contract-only orchestration between composition and runtime subsystems."""

from .experiment_matrix import (
    BuildJobResult,
    ExperimentMatrixError,
    ExperimentRunner,
    FuzzJobResult,
    ResourceCheckpointEvent,
    ResourceTerminatedError,
    RunnerResult,
    matrix_promotion_pairs,
    run_experiment_matrix,
)
from .pipeline import GenerationRequest, RuntimeRequest, run_candidate_pipeline
from .low_resource_smoke import run_generic_composition_smoke, run_low_resource_smoke
from .campaign import (
    CampaignError,
    CampaignLimits,
    CampaignOptions,
    read_process_group_rss_bytes,
    read_rss_bytes,
    run_supervised_command,
)
from .rfuzz_runner import RfuzzExperimentRunner
from .reference_adapter import (
    GeneratorCommand,
    GeneratorFlag,
    GeneratorPathArgument,
    GeneratorPathSyntax,
    ReferenceAdapter,
    assert_reference_not_in_generator_argv,
)
from .semantic_projection import (
    assert_semantic_rename_invariant,
    semantic_projection,
)
from .riscv_execution import (
    BootImage,
    ExecutionEvent,
    RiscvExecutionError,
    RiscvExecutionEvent,
    RiscvExecutionFacts,
    RiscvExecutionProvenance,
    build_minimal_boot_image,
    build_protocol_blocker,
    build_run_manifest,
    verify_execution_events,
    verify_repository_pins,
)
from .soc_campaign import (
    SOC_RESULT_SCHEMA,
    SocCampaignError,
    SocCampaignProtocolError,
    SocCampaignSoftwareTrap,
    preflight_soc_campaign,
    run_soc_campaign,
)
from .soc_comparison import (
    ARM_NAMES,
    COMPARISON_SCHEMA,
    SocComparisonError,
    compare_soc_campaign_arms,
    replay_official_corpus_arms,
)
from .soc_coverage import (
    COVERAGE_SCHEMA,
    CoveragePoint,
    SocCoverageError,
    build_coverage_universe,
    coverage_delta,
    coverage_feedback_document,
    observe_rtl_coverage,
)

__all__ = [
    "BuildJobResult",
    "BootImage",
    "CampaignError",
    "CampaignLimits",
    "CampaignOptions",
    "ExperimentMatrixError",
    "ExperimentRunner",
    "ExecutionEvent",
    "RiscvExecutionEvent",
    "FuzzJobResult",
    "GenerationRequest",
    "GeneratorCommand",
    "GeneratorFlag",
    "GeneratorPathArgument",
    "GeneratorPathSyntax",
    "ReferenceAdapter",
    "RiscvExecutionError",
    "RiscvExecutionFacts",
    "RiscvExecutionProvenance",
    "RfuzzExperimentRunner",
    "ResourceCheckpointEvent",
    "ResourceTerminatedError",
    "RunnerResult",
    "RuntimeRequest",
    "assert_semantic_rename_invariant",
    "assert_reference_not_in_generator_argv",
    "build_minimal_boot_image",
    "build_protocol_blocker",
    "build_run_manifest",
    "matrix_promotion_pairs",
    "run_candidate_pipeline",
    "run_experiment_matrix",
    "run_low_resource_smoke",
    "run_generic_composition_smoke",
    "read_process_group_rss_bytes",
    "read_rss_bytes",
    "run_supervised_command",
    "semantic_projection",
    "verify_execution_events",
    "verify_repository_pins",
    "SOC_RESULT_SCHEMA",
    "SocCampaignError",
    "SocCampaignProtocolError",
    "SocCampaignSoftwareTrap",
    "preflight_soc_campaign",
    "run_soc_campaign",
    "ARM_NAMES",
    "COMPARISON_SCHEMA",
    "SocComparisonError",
    "compare_soc_campaign_arms",
    "replay_official_corpus_arms",
    "COVERAGE_SCHEMA",
    "CoveragePoint",
    "SocCoverageError",
    "build_coverage_universe",
    "coverage_delta",
    "coverage_feedback_document",
    "observe_rtl_coverage",
]
