"""Incremental observed-result checks for the reset-free Ibex/UART pilot."""

from __future__ import annotations

from collections import deque
from collections.abc import Mapping

from .session_runtime import OnlineCaseReceipt


class IbexUartOnlineChecker:
    """Check real RXDATA delivery and Ibex consumption across case boundaries.

    A missing IRQ, ISR, or read remains coverage feedback, not a DUT finding.
    An accepted RXDATA read, however, must return the FIFO head supplied by
    the recorded external 8N1 source, and CPU response data must equal that
    real UART read. No value is generated by this checker.
    """

    def __init__(self) -> None:
        self._last_event_id = 0
        self._case_results: dict[str, tuple[tuple[dict, ...], tuple[str, ...]]] = {}
        self._expected_rx: deque[int] = deque()
        self._reads: dict[tuple[int, int], int] = {}

    def __call__(self, receipt: OnlineCaseReceipt) -> tuple[str, ...]:
        if not isinstance(receipt, OnlineCaseReceipt):
            raise ValueError("online case receipt is required")
        prior = self._case_results.get(receipt.case_id)
        if prior is not None:
            if prior[0] != receipt.events:
                raise ValueError("online case ID reused with different UART events")
            return prior[1]
        findings: list[str] = []
        for event in receipt.events:
            event_id = event.get("event_id")
            if type(event_id) is not int or event_id <= self._last_event_id:
                raise ValueError("online UART event IDs must increase")
            self._last_event_id = event_id
            if event.get("kind") == "reset_barrier":
                self._expected_rx.clear()
                self._reads.clear()
                continue
            if (event.get("kind") == "source_injection"
                    and event.get("component") == "uart"
                    and event.get("port") == "uart_rx_byte"
                    and event.get("width") == 8
                    and event.get("bit_offset") == 0
                    and type(event.get("value")) is int):
                self._expected_rx.append(event["value"])
            if (event.get("kind") == "mmio_delivery"
                    and event.get("device_id") == "uart"
                    and event.get("write") is False
                    and event.get("offset") == 0x18
                    and type(event.get("read_value")) is int):
                actual = event["read_value"] & 0xff
                if self._expected_rx:
                    expected = self._expected_rx.popleft()
                    if actual != expected:
                        findings.append("uart_rxdata_source_mismatch")
                tx = event.get("source_transaction")
                if isinstance(tx, Mapping):
                    epoch, sequence = tx.get("source_epoch"), tx.get("source_sequence")
                    if type(epoch) is int and type(sequence) is int:
                        self._reads[(epoch, sequence)] = event["read_value"]
            outputs = event.get("outputs")
            if (event.get("component") == "cpu" and event.get("kind") is None
                    and isinstance(outputs, Mapping)
                    and outputs.get("data_rsp_consumed") == 1):
                epoch, sequence = (outputs.get("data_rsp_source_epoch"),
                                   outputs.get("data_rsp_source_sequence"))
                if type(epoch) is int and type(sequence) is int:
                    expected = self._reads.pop((epoch, sequence), None)
                    if (expected is not None and type(outputs.get("data_rsp_rdata")) is int
                            and outputs["data_rsp_rdata"] != expected):
                        findings.append("cpu_uart_rxdata_response_mismatch")
        result = tuple(dict.fromkeys(findings))
        self._case_results[receipt.case_id] = (receipt.events, result)
        return result
