// Stub file for prim_assert.sv
// 用于synthesis时禁用assertion

`ifndef PRIM_ASSERT_SV
`define PRIM_ASSERT_SV

// 在synthesis模式下，将所有assertion宏定义为空
`ifdef SYNTHESIS
  `define ASSERT(NAME, PROP, CLK = `ASSERT_DEFAULT_CLK, RST = `ASSERT_DEFAULT_RST)
  `define ASSERT_NEVER(NAME, PROP, CLK = `ASSERT_DEFAULT_CLK, RST = `ASSERT_DEFAULT_RST)
  `define ASSERT_KNOWN(NAME, SIGNAL, CLK = `ASSERT_DEFAULT_CLK, RST = `ASSERT_DEFAULT_RST)
  `define ASSERT_KNOWN_IF(NAME, SIGNAL, COND, CLK = `ASSERT_DEFAULT_CLK, RST = `ASSERT_DEFAULT_RST)
  `define ASSERT_IF(NAME, PROP, COND, CLK = `ASSERT_DEFAULT_CLK, RST = `ASSERT_DEFAULT_RST)
  `define ASSERT_INIT(NAME, PROP)
  `define ASSERT_FINAL(NAME, PROP)
  `define ASSERT_STATIC_IN_PACKAGE(NAME, PROP)
  `define ASSERT_PULSE(NAME, SIG, CLK = `ASSERT_DEFAULT_CLK, RST = `ASSERT_DEFAULT_RST)
  `define ASSERT_PRIM_COUNT_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_DOUBLE_LFSR_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_FSM_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_ONEHOT_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_FIFO_SYNC_SINGLETON_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_COUNT_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_DOUBLE_LFSR_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_FSM_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_ONEHOT_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_FIFO_SYNC_SINGLETON_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_FSM_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE = 0, MAX_CYCLES = 2, CLK = clk_i, RST = !rst_ni)
  `define ASSERT_PRIM_COUNT_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE = 0, MAX_CYCLES = 2, CLK = clk_i, RST = !rst_ni)
  `define ASSERT_PRIM_DOUBLE_LFSR_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE = 0, MAX_CYCLES = 2, CLK = clk_i, RST = !rst_ni)
  `define ASSERT_PRIM_ONEHOT_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE = 0, MAX_CYCLES = 2, CLK = clk_i, RST = !rst_ni)
  `define ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE = 0, MAX_CYCLES = 2, CLK = clk_i, RST = !rst_ni)
  `define ASSERT_PRIM_FIFO_SYNC_ERROR_TRIGGERS_ALERT(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_FIFO_SYNC_ERROR_TRIGGERS_ALERT1(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define ASSERT_PRIM_FIFO_SYNC_ERROR_TRIGGERS_ALERT1_IN(NAME, HIER, ALERT, GATE = 0, MAX_CYCLES = 2)
  `define COVER(NAME, PROP, CLK = `ASSERT_DEFAULT_CLK, RST = `ASSERT_DEFAULT_RST)
  `define ASSUME(NAME, PROP, CLK = `ASSERT_DEFAULT_CLK, RST = `ASSERT_DEFAULT_RST)
  `define ASSUME_I(NAME, PROP)
  `define ASSERT_RPT(NAME, PROP, RPT, CLK = `ASSERT_DEFAULT_CLK, RST = `ASSERT_DEFAULT_RST)
`else
  // 非synthesis模式也定义为空（简化）
  `define ASSERT(NAME, PROP, CLK, RST)
  `define ASSERT_NEVER(NAME, PROP, CLK, RST)
  `define ASSERT_KNOWN(NAME, SIGNAL, CLK, RST)
  `define ASSERT_KNOWN_IF(NAME, SIGNAL, COND, CLK, RST)
  `define ASSERT_IF(NAME, PROP, COND, CLK, RST)
  `define ASSERT_INIT(NAME, PROP)
  `define ASSERT_FINAL(NAME, PROP)
  `define ASSERT_STATIC_IN_PACKAGE(NAME, PROP)
  `define ASSERT_PULSE(NAME, SIG, CLK, RST)
  `define ASSERT_PRIM_COUNT_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_DOUBLE_LFSR_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_FSM_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_ONEHOT_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_FIFO_SYNC_SINGLETON_ERROR_TRIGGER_ALERT(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_COUNT_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_DOUBLE_LFSR_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_FSM_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_ONEHOT_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_FIFO_SYNC_SINGLETON_ERROR_TRIGGER_ALERT_IN(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_FSM_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE, MAX_CYCLES, CLK, RST)
  `define ASSERT_PRIM_COUNT_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE, MAX_CYCLES, CLK, RST)
  `define ASSERT_PRIM_DOUBLE_LFSR_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE, MAX_CYCLES, CLK, RST)
  `define ASSERT_PRIM_ONEHOT_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE, MAX_CYCLES, CLK, RST)
  `define ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ERR(NAME, HIER, ERR, GATE, MAX_CYCLES, CLK, RST)
  `define ASSERT_PRIM_FIFO_SYNC_ERROR_TRIGGERS_ALERT(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_FIFO_SYNC_ERROR_TRIGGERS_ALERT1(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define ASSERT_PRIM_FIFO_SYNC_ERROR_TRIGGERS_ALERT1_IN(NAME, HIER, ALERT, GATE, MAX_CYCLES)
  `define COVER(NAME, PROP, CLK, RST)
  `define ASSUME(NAME, PROP, CLK, RST)
  `define ASSUME_I(NAME, PROP)
  `define ASSERT_RPT(NAME, PROP, RPT, CLK, RST)
`endif

`define ASSERT_DEFAULT_CLK clk_i
`define ASSERT_DEFAULT_RST !rst_ni

`endif // PRIM_ASSERT_SV
