+incdir+../upstream/ultraembedded_riscv/core
../upstream/ultraembedded_riscv/core/riscv_defs.v
../upstream/ultraembedded_riscv/core/riscv_alu.v
../upstream/ultraembedded_riscv/core/riscv_csr_regfile.v
../upstream/ultraembedded_riscv/core/riscv_csr.v
../upstream/ultraembedded_riscv/core/riscv_decode.v
../upstream/ultraembedded_riscv/core/riscv_decoder.v
../upstream/ultraembedded_riscv/core/riscv_divider.v
../upstream/ultraembedded_riscv/core/riscv_exec.v
../upstream/ultraembedded_riscv/core/riscv_fetch.v
../upstream/ultraembedded_riscv/core/riscv_trace_sim.v
../upstream/ultraembedded_riscv/core/riscv_issue.v
../upstream/ultraembedded_riscv/core/riscv_lsu.v
../upstream/ultraembedded_riscv/core/riscv_mmu.v
../upstream/ultraembedded_riscv/core/riscv_multiplier.v
../upstream/ultraembedded_riscv/core/riscv_pipe_ctrl.v
../upstream/ultraembedded_riscv/core/riscv_regfile.v
../upstream/ultraembedded_riscv/core/riscv_core.v
../upstream/ultraembedded_riscv/tcm/dport_axi.v
../upstream/ultraembedded_riscv/tcm/dport_mux.v
../upstream/ultraembedded_riscv/tcm/tcm_mem_pmem.v
../upstream/ultraembedded_riscv/tcm/tcm_mem_ram.v
../upstream/ultraembedded_riscv/tcm/tcm_mem.v
../upstream/ultraembedded_riscv/tcm/riscv_tcm_top.v
../wrappers/ultra_riscv_axil_cpu_wrapper.sv
